language: php

php:
  - 5.5
  - 5.6
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  - composer install -n

script:
  - phpunit -c app
  - ./home/travis/build/EBMCentraleLille/fablab/vendor/bin/phpcs -h
  - phpcs -h
