language: php

php:
  - 5.5
  - 5.6
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  - composer install -n
  - composer global require "squizlabs/php_codesniffer=*"

script:
  - phpunit -c app
  - ./vendor/bin/phpcs -h
