language: php

php:
  - 5.5
  - 5.6
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

services:
  - mysql

before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install -n
  - php app/console doctrine:database:create
  - php app/console doctrine:schema:create
  - php app/console doctrine:fixtures:load

script:
  - phpunit -c app
  - ./vendor/squizlabs/php_codesniffer/scripts/phpcs src/
