language: php

php:
  - 5.5
  - 5.6
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  - composer install -n

script:
  - phpunit -c app
  - ./vendor/squizlabs/php_codesniffer/scripts/phpcs src/
