CentraleLille\CustomFosUserBundle\Entity\User:
  exclusion_policy : ALL
  properties:
    id:
      expose: true
    username:
      expose: true
    firstname:
      expose: true
    lastname:
      expose: true