service_task:
  type: rest
  prefix: /api
  resource: CentraleLille\GdpBundle\Controller\TaskController

service_user:
  type: rest
  prefix: /api
  resource: CentraleLille\GdpBundle\Controller\UserController

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
