service_task:
  type: rest
  prefix: /api
  resource: CentraleLille\GdpBundle\Controller\TaskController

service_event:
  type: rest
  prefix: /api
  resource: CentraleLille\GdpBundle\Controller\EventController

service_list:
  type: rest
  prefix: /api
  resource: CentraleLille\GdpBundle\Controller\TaskListController

service_user:
  type: rest
  prefix: /api
  resource: CentraleLille\GdpBundle\Controller\UserController

service_project:
  type : rest
  prefix: /api
  resource: CentraleLille\GdpBundle\Controller\ProjectController

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
