service_task:
  type: rest
  prefix: /api
  resource: CentraleLille\GdpBundle\Controller\TaskController

service_project:
  type : rest
  prefix: /api
  resource: CentraleLille\GdpBundle\Controller\ProjectController

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
