services:
#    centrale_lille_gdp.example:
#        class: CentraleLille\GdpBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    service.task:
      class: CentraleLille\GdpBundle\TaskService
      arguments: ["@doctrine.orm.default_entity_manager"]