<?php

namespace CentraleLille\ReservationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CasierRepository extends EntityRepository
{
}
