<?php

namespace CentraleLille\ReservationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MarchineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MachineRepository extends EntityRepository
{
}
