centrale_lille_homepage_homepage:
    path:     /
    defaults: { _controller: CentraleLilleHomepageBundle:Homepage:index }
centrale_lille_homepage_category:
    path:     /category/{category}
    defaults: { _controller: CentraleLilleHomepageBundle:Homepage:category }
