services:
    fablab_homepage.starProject:
        class: CentraleLille\HomepageBundle\Services\FablabStarProject
        arguments: ['@doctrine.orm.entity_manager']
    fablab_homepage.recentProject:
        class: CentraleLille\HomepageBundle\Services\FablabRecentProject
        arguments: ['@doctrine.orm.entity_manager']