<?php

namespace CentraleLille\GdpBundle\Repository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;

class TaskRepository extends EntityRepository
{
    public function findFiveTasks()
    {
        $queryBuilder = $this->createQueryBuilder('t');

        //add condition to get only last five tasks

        return $queryBuilder
            ->getQuery()
            ->getResult()
            ;

    }
}