<?php

namespace CentraleLille\NewsFeedBundle\Repository;

/**
 * CatFollowsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatFollowsRepository extends \Doctrine\ORM\EntityRepository
{
}
