<?php

namespace CentraleLille\NewsFeedBundle\Repository;

/**
 * ProjFollowsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjFollowsRepository extends \Doctrine\ORM\EntityRepository
{
}
