<?php

namespace CentraleLille\HomepageBundle\Repository;

/**
 * StarProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StarProjectRepository extends \Doctrine\ORM\EntityRepository
{
}
