<?php

namespace CentraleLille\KnowledgeBundle\Repository;

use CentraleLille\CustomFosUserBundle\Entity\User;
use CentraleLille\KnowledgeBundle\Entity\Competence;

/**
 * CompetenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetenceRepository extends \Doctrine\ORM\EntityRepository
{
}
