<?php

namespace CentraleLille\KnowledgeBundle\Repository;

/**
 * ForumPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumThreadRepository extends \Doctrine\ORM\EntityRepository
{
}
