<?php

namespace CentraleLille\KnowledgeBundle\Repository;

/**
 * ForumPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumPostRepository extends \Doctrine\ORM\EntityRepository
{
}
