<?php

namespace CentraleLille\KnowledgeBundle\Repository;

use CentraleLille\KnowledgeBundle\Entity\Competence;
/**
 * UserCompetenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCompetenceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllCompetencesInUserCompetencesDQL(Competence $competence)
    {
        $query = $this->_em->createQuery('SELECT c FROM CentraleLilleKnowledgeBundle:UserCompetence c JOIN c.competence b WHERE b.id = :competence');
        $query->setParameter('competence', $competence->getId());
        $results = $query->getResult();

        return $results;
    }
}
