<?php

namespace CentraleLille\KnowledgeBundle\Repository;

/**
 * UserCompetenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCompetenceRepository extends \Doctrine\ORM\EntityRepository
{
}
