<?php

namespace CentraleLille\SearchBundle\Repository;

/**
 * DemoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemoRepository extends \Doctrine\ORM\EntityRepository
{
}
