project_page_homepage:
    path:     /{projectId}
    defaults: { _controller: ProjectPageBundle:ProjectPage:displayProject }
project_page_delete_activity:
    path:     /{projectId}/delete/{activityId}
    defaults: { _controller: ProjectPageBundle:ProjectPage:deleteActivity }